In [130]:
# from sklearn.datasets import load_boston   # 从sklearn.datasets导入失效

In [131]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error 
# from sklearn.externals import joblib
import joblib

In [132]:
# 导入数据
boston = pd.read_csv("../data/boston/boston.csv")
boston

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PIRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [133]:
# 特征值
x = boston.drop(["MEDV"], axis=1)
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PIRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [134]:
# 目标值
y = boston["MEDV"]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [135]:
# 数据集划分
x_train, x_test, y_train, y_test = train_test_split(x, y)
# 标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [136]:
# 模型训练
# estimator = Ridge(alpha=0.5, max_iter=10000)
# estimator.fit(x_train, y_train)

In [137]:
# 保存模型
# joblib.dump(estimator, "my_ridge.pkl")

In [138]:
# 加载模型
estimator = joblib.load("my_ridge.pkl")

In [139]:
# 模型参数
print("权重系数为：\n", estimator.coef_)
print("偏置为：\n", estimator.intercept_)

权重系数为：
 [-0.98263554  1.29042128  0.03810422  0.78854898 -2.3535038   2.32867861
 -0.00507028 -3.64230771  2.96250072 -2.0887139  -2.15425636  0.99159383
 -3.76971151]
偏置为：
 22.58179419525066

In [140]:
# 模型评估-均方误差
y_predict = estimator.predict(x_test)
print("预测房价：\n", y_predict)
error = mean_squared_error(y_test, y_predict)
print("正规方程-均方误差为：\n", error)

预测房价：
 [14.03675976 22.49728278 35.81775852 16.52271752 16.92190865 26.44385776
 18.49552585 11.78616268 25.11838707  9.39408032 25.42772497 16.22727951
 25.47004555 12.25896912 31.61955173 33.12941146 12.56903372 31.24924527
 36.19390561  4.36824696 28.37569118 29.29753735 19.55518911 23.89676644
 19.1741999  23.43010257 27.92395565 17.14086658 26.98231354 13.3302018
 19.55512985  9.47249212 28.87141972 18.85927208 36.73638164 19.74203705
 22.76848537  8.37275578 23.44815466 40.36404449 34.69026003 12.74699969
 29.60677325 19.93765384 13.94775556 19.27435568 13.78164293 23.68959043
 15.72323037 21.10353819 26.10364745 18.81851659 24.35365464 25.61677937
 18.10738604 27.07341511 20.23710594 22.87155384 20.58381774 22.0323964
 13.66975364 22.42660805  7.88378425 34.39489252 25.00732263 19.28730569
 31.44537914 36.92486195 25.76578412 20.77213905  7.21209745  7.23443369
 32.28360773 17.15542771 19.89833984 31.7093473  27.90809477 20.33592244
 14.29879418 12.80068305 14.0579433  15.44455712 21.70829814 14.87172185
 25.4895503  18.33343285 23.87808492 27.12115416 22.6355013  43.26318948
 29.0287973  21.84530848 18.68369289 22.56793902 33.27846125 27.31765775
 17.87521443 34.66118653 28.35150843 24.67821765 32.49359674 23.52116378
 16.0499092  15.69329797 24.69738521 26.8879029   8.21327326 24.67513906
 21.5822122  33.82856582 19.06992105 19.93590779 18.650845   32.92526516
 26.75433048 27.23607785 19.04280889 17.44809701 21.09711963 11.3412301
 19.25991463 29.9190742  30.7257436  18.96786015 22.35187688 12.41085186
 29.11511777]
正规方程-均方误差为：
 19.4571182005329